# Generated by Django 2.2.14 on 2021-11-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rope', '0002_address_user_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user_number',
            field=models.CharField(default=True, max_length=10,null=True, blank=True),
        ),
    ]
