# Generated by Django 2.2.14 on 2021-11-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rope', '0003_auto_20211112_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user_number',
            field=models.CharField(blank=True, default=True, max_length=10, null=True),
        ),
    ]
